import { TenseData } from "./types";

export const TENSES: TenseData[] = [
  {
    id: "present-simple",
    title: "Present Simple",
    description: "Oddiy hozirgi zamon.",
    usage: ["Doimiy ishlar (habit)", "Faktlar (haqiqatlar)", "Jadval, reja"],
    formula: {
      positive: "Subject + Verb (V1)",
      negative: "Subject + do/does + not + V1",
      question: "Do/Does + Subject + V1 ?",
    },
    examples: [
      { en: "I work", uz: "Men ishlayman" },
      { en: "He works", uz: "U ishlaydi" },
      { en: "She likes tea", uz: "U choyni yaxshi ko'radi" },
      { en: "It rains", uz: "Yomg'ir yog'adi" },
    ],
    rules: [
      "Agar He / She / It bo'lsa → verbga -s / -es qo'shiladi",
      "Agar fe'l -sh, -ch, -ss, -x, -o bilan tugasa -es qo'shiladi (go → goes, watch → watches)",
      "does bo'lsa, fe'lga s qo'shilmaydi!",
    ],
    signalWords: ["always", "usually", "often", "sometimes", "never"],
    commonMistakes: [
      { wrong: "He go to school", correct: "He goes to school" },
      { wrong: "He doesn't goes", correct: "He doesn't go" },
      { wrong: "Does he goes?", correct: "Does he go?" },
    ],
    miniExercise: [
      { question: "Men har kuni o'qiyman", answer: "I study every day" },
      { question: "U futbol o'ynaydi", answer: "He plays football" },
      { question: "Biz ishlamaymiz", answer: "We don't work" },
      { question: "U choy ichadimi?", answer: "Does he drink tea?" },
    ],
    practiceSentences: [
      "Men har kuni ertalab soat 6 da uyg'onaman.",
      "Mening akam bankda ishlaydi.",
      "Ular har yakshanba kuni futbol o'ynashadi.",
      "Biz kechqurun televizor ko'rmaymiz.",
      "Siz ingliz tilida gapirasizmi?",
      "Suv 100 darajada qaynaydi.",
      "U har doim maktabga kechikib keladi.",
      "Mening onam mazali ovqatlar pishiradi.",
      "Poyezd soat 9 da jo'nab ketadi.",
      "Siz qayerda yashaysiz?"
    ],
    lifehack: "He/She/It = +S | Does = S yo'q",
  },
  {
    id: "present-continuous",
    title: "Present Continuous",
    description: "Hozir ayni paytda bo'layotgan ish.",
    usage: ["Hozir ayni paytda", "Vaqtincha ishlar", "Hozirgi o'zgarishlar"],
    formula: {
      positive: "Subject + am / is / are + V-ing",
      negative: "Subject + am/is/are + not + V-ing",
      question: "Am / Is / Are + Subject + V-ing?",
    },
    examples: [
      { en: "I am studying", uz: "Men hozir o'qiyapman" },
      { en: "He is working", uz: "U hozir ishlayapti" },
      { en: "They are playing", uz: "Ular o'ynayapti" },
    ],
    rules: [
      "I + am, He/She/It + is, You/We/They + are",
      "-ing qo'shishda 'e' tushadi (write → writing)",
      "Oxiri 1 unli + 1 undosh bo'lsa, undosh 2 marta yoziladi (run → running)",
    ],
    signalWords: ["now", "at the moment", "right now", "currently"],
    commonMistakes: [
      { wrong: "I am study", correct: "I am studying" },
      { wrong: "He is play", correct: "He is playing" },
      { wrong: "She playing", correct: "She is playing" },
    ],
    miniExercise: [
      { question: "Men hozir ovqat yeyapman", answer: "I am eating now" },
      { question: "U televizor ko'rayapti", answer: "He is watching TV" },
      { question: "Biz ishlamayapmiz", answer: "We are not working" },
      { question: "Sen o'qiyapsanmi?", answer: "Are you studying?" },
    ],
    practiceSentences: [
      "Men hozir kitob o'qiyapman.",
      "Ular tashqarida futbol o'ynashyapti.",
      "Onam oshxonada ovqat pishiryapti.",
      "Siz nima qilyapsiz?",
      "Yomg'ir yog'yapti.",
      "Biz hozir dars tayyorlayapmiz.",
      "U telefonda gaplashyapti.",
      "Bolalar uxlayaptimi?",
      "Men bugun ishlamayapman.",
      "Havo soviyapti."
    ],
    lifehack: "am / is / are + verb + ing = har doim bor",
  },
  {
    id: "present-perfect",
    title: "Present Perfect",
    description: "O'tmishda bo'lgan, lekin hozir bilan bog'liq (natija muhim).",
    usage: ["Natija hozir muhim", "Tajriba (hayotda qilgan ishlar)", "Hali davom etayotgan ish"],
    formula: {
      positive: "Subject + have / has + V3",
      negative: "Subject + have/has + not + V3",
      question: "Have / Has + Subject + V3?",
    },
    examples: [
      { en: "I have finished my work", uz: "Men ishni tugatdim (natija bor)" },
      { en: "He has gone to school", uz: "U maktabga ketgan (hali u yerda)" },
      { en: "They have seen this film", uz: "Ular bu filmni ko'rgan" },
    ],
    rules: [
      "I/You/We/They + have, He/She/It + has",
      "V3 - fe'lning 3-shakli (Past Participle)",
      "Qachonligi muhim emas, natija muhim!",
    ],
    signalWords: ["already", "just", "yet", "ever", "never", "for", "since"],
    commonMistakes: [
      { wrong: "I have went", correct: "I have gone" },
      { wrong: "He have done", correct: "He has done" },
      { wrong: "I am finished", correct: "I have finished" },
    ],
    miniExercise: [
      { question: "Men ovqat yeb bo'ldim", answer: "I have eaten" },
      { question: "U hali kelmagan", answer: "He hasn't come yet" },
      { question: "Sen bu filmni ko'rganmisan?", answer: "Have you seen this film?" },
      { question: "Biz bu yerda 2 yildan beri yashaymiz", answer: "We have lived here for 2 years" },
    ],
    practiceSentences: [
      "Men uy vazifamni tugatdim.",
      "U allaqachon Toshkentga ketgan.",
      "Siz hech qachon Londonda bo'lganmisiz?",
      "Ular bu filmni ko'rishgan.",
      "Men hali ovqat yemadim.",
      "Biz bu yerda besh yildan beri yashaymiz.",
      "U kalitini yo'qotib qo'ydi.",
      "Siz bu kitobni o'qib bo'ldingizmi?",
      "Men hozirgina do'stimni ko'rdim.",
      "Ular hali kelishmadi."
    ],
    lifehack: "have/has + V3 = natija hozir muhim!",
  },
  {
    id: "present-perfect-continuous",
    title: "Present Perfect Continuous",
    description: "O'tmishda boshlangan va hozirgacha davom etayotgan ish.",
    usage: ["Davomiylik (qancha vaqt)", "Hozir natijasi ko'rinib turibdi"],
    formula: {
      positive: "Subject + have/has + been + V-ing",
      negative: "Subject + have/has + not + been + V-ing",
      question: "Have/Has + Subject + been + V-ing?",
    },
    examples: [
      { en: "I have been studying", uz: "Men o'qib kelayapman" },
      { en: "He has been working", uz: "U ishlab kelayapti" },
      { en: "They have been playing", uz: "Ular o'ynab kelayapti" },
    ],
    rules: [
      "have/has been + V-ing",
      "Jarayon muhim (Present Perfectda natija muhim)",
    ],
    signalWords: ["for", "since", "recently", "lately"],
    commonMistakes: [
      { wrong: "I have been study", correct: "I have been studying" },
      { wrong: "He has been work", correct: "He has been working" },
      { wrong: "I am been working", correct: "I have been working" },
    ],
    miniExercise: [
      { question: "Men 3 soatdan beri o'qiyapman", answer: "I have been studying for 3 hours" },
      { question: "U ertalabdan beri ishlayapti", answer: "He has been working since morning" },
      { question: "Sen qancha vaqtdan beri ingliz o'rganayapsan?", answer: "How long have you been learning English?" },
      { question: "Biz kutib turibmiz (ancha vaqt)", answer: "We have been waiting" },
    ],
    practiceSentences: [
      "Men ikki soatdan beri kitob o'qiyapman.",
      "U ertalabdan beri ishlayapti.",
      "Ular ancha vaqtdan beri futbol o'ynashyapti.",
      "Siz qancha vaqtdan beri kutib turibsiz?",
      "Yomg'ir tun bo'yi yog'yapti.",
      "Men bir yildan beri ingliz tilini o'rganyapman.",
      "Ular yaqindan beri bu yerda yashashyapti.",
      "Siz nega charchadingiz? Chunki men yugurib keldim.",
      "Biz dushanbadan beri shu loyiha ustida ishlayapmiz.",
      "U uch kundan beri uxlamayapti."
    ],
    lifehack: "have/has been + verb + ing | for / since = 90% shu zamon",
  },
  {
    id: "past-simple",
    title: "Past Simple",
    description: "O'tgan zamonda bo'lib tugagan ishlar.",
    usage: ["Aniq o'tgan vaqt (yesterday, last week)", "Tugagan ish"],
    formula: {
      positive: "Subject + V2",
      negative: "Subject + did not + V1",
      question: "Did + Subject + V1?",
    },
    examples: [
      { en: "I worked yesterday", uz: "Men kecha ishladim" },
      { en: "He went to school", uz: "U maktabga bordi" },
      { en: "They watched a movie", uz: "Ular film ko'rdi" },
    ],
    rules: [
      "V2 - fe'lning o'tgan zamon shakli",
      "Regular fe'llarga -ed qo'shiladi (work → worked)",
      "Irregular fe'llarni yodlash kerak (go → went)",
      "did bo'lsa, V1 ishlatiladi!",
    ],
    signalWords: ["yesterday", "last night/week/year", "ago", "in (year)"],
    commonMistakes: [
      { wrong: "I did not went", correct: "I did not go" },
      { wrong: "Did you went?", correct: "Did you go?" },
      { wrong: "He go yesterday", correct: "He went yesterday" },
    ],
    miniExercise: [
      { question: "Men kecha futbol o'ynadim", answer: "I played football yesterday" },
      { question: "U maktabga bordi", answer: "He went to school" },
      { question: "Biz ishlamadik", answer: "We didn't work" },
      { question: "Sen film ko'rdingmi?", answer: "Did you watch a movie?" },
    ],
    practiceSentences: [
      "Men kecha do'stimni ko'rdim.",
      "Ular o'tgan hafta Toshkentga borishdi.",
      "Men ikki kun oldin kitob sotib oldim.",
      "Siz kecha nima qildingiz?",
      "U maktabni o'tgan yili tugatdi.",
      "Biz kecha futbol o'ynamadik.",
      "Ular soat 7 da ovqatlanishdi.",
      "Men bu filmni ko'rganman (o'tgan zamonda).",
      "Siz kecha darsga keldingizmi?",
      "U menga qo'ng'iroq qilmadi."
    ],
    lifehack: "Positive → V2 | Negative / Question → did + V1",
  },
  {
    id: "past-continuous",
    title: "Past Continuous",
    description: "O'tmishda ma'lum bir vaqtda davom etayotgan ish.",
    usage: ["Aniq vaqt davomida", "Boshqa ish bilan birga (when/while)", "Ikki ish birga davom etishi"],
    formula: {
      positive: "Subject + was / were + V-ing",
      negative: "Subject + was/were + not + V-ing",
      question: "Was/Were + Subject + V-ing?",
    },
    examples: [
      { en: "I was studying", uz: "Men o'qiyotgan edim" },
      { en: "He was working", uz: "U ishlayotgan edi" },
      { en: "They were playing", uz: "Ular o'ynayotgan edi" },
    ],
    rules: [
      "I/He/She/It + was, You/We/They + were",
      "Bir ish davom etayotganda, boshqa ish bo'ldi (when)",
    ],
    signalWords: ["while", "when", "at that moment", "at 5 pm"],
    commonMistakes: [
      { wrong: "I was study", correct: "I was studying" },
      { wrong: "They was playing", correct: "They were playing" },
      { wrong: "Was you studying?", correct: "Were you studying?" },
    ],
    miniExercise: [
      { question: "Men kecha o'qiyotgan edim", answer: "I was studying yesterday" },
      { question: "U ishlamayotgan edi", answer: "He was not working" },
      { question: "Sen uxlayotganmiding?", answer: "Were you sleeping?" },
      { question: "Men o'qiyotgan edim, u kelib qoldi", answer: "I was studying when he came" },
    ],
    practiceSentences: [
      "Men kecha soat 8 da kitob o'qiyotgan edim.",
      "Ular futbol o'ynayotgan edilar.",
      "Men ovqat pishirayotganimda, telefon jiringladi.",
      "Siz soat 10 da nima qilayotgan edingiz?",
      "U uxlayotgan edi.",
      "Biz dars tayyorlayotgan edik.",
      "Ular gaplashib o'tirishgan edi.",
      "Yomg'ir yog'ayotgan edi.",
      "Siz meni kutayotganmidingiz?",
      "Men ishlamayotgan edim."
    ],
    lifehack: "was/were + V-ing = o'tgan zamon davom",
  },
  {
    id: "past-perfect",
    title: "Past Perfect",
    description: "O'tmishda bir ish boshqa ishdan oldin bo'lib tugagan.",
    usage: ["Ikki o'tgan ish (biridan oldin bo'lgani)", "when / before / after bilan"],
    formula: {
      positive: "Subject + had + V3",
      negative: "Subject + had not + V3",
      question: "Had + Subject + V3?",
    },
    examples: [
      { en: "I had finished my work", uz: "Men ishni tugatgan edim" },
      { en: "He had gone to school", uz: "U maktabga ketgan edi" },
      { en: "They had eaten", uz: "Ular ovqat yegan edi" },
    ],
    rules: [
      "Hamma subject bilan 'had' ishlatiladi",
      "2 ta o'tgan ish bo'lsa, oldingisi Past Perfect bo'ladi",
    ],
    signalWords: ["before", "after", "when", "already"],
    commonMistakes: [
      { wrong: "I had went", correct: "I had gone" },
      { wrong: "He had did", correct: "He had done" },
      { wrong: "I had finish", correct: "I had finished" },
    ],
    miniExercise: [
      { question: "Men kelishimdan oldin u ketgan edi", answer: "He had gone before I came" },
      { question: "U ovqat yeb bo'lgan edi", answer: "He had eaten" },
      { question: "Sen uy vazifani qilganmiding?", answer: "Had you done your homework?" },
      { question: "Biz film boshlanishidan oldin kelgan edik", answer: "We had come before the film started" },
    ],
    practiceSentences: [
      "Men kelgunimcha, u ketib bo'lgan edi.",
      "Biz yetib borganimizda, film boshlanib bo'lgan edi.",
      "U ovqat yeb bo'lgan edi.",
      "Men uy vazifamni tugatgan edim.",
      "Siz u kelishidan oldin darsni bitirganmidingiz?",
      "Ular Toshkentga borishgan edi.",
      "Men bu kitobni o'qib bo'lgan edim.",
      "U menga qo'ng'iroq qilgan edi.",
      "Biz uchrashgunimizcha, u hamma narsani hal qilgan edi.",
      "Ular hali kelishmagan edi."
    ],
    lifehack: "had + V3 | 2 ta o'tgan ish → oldingisi Past Perfect",
  },
  {
    id: "past-perfect-continuous",
    title: "Past Perfect Continuous",
    description: "O'tmishda bir ish boshqa ishdan OLDIN uzoq vaqt davom etgan.",
    usage: ["Davomiylik (qancha vaqt davom etib kelgan)", "Sabab (natija ko'rinadi)"],
    formula: {
      positive: "Subject + had been + V-ing",
      negative: "Subject + had not + been + V-ing",
      question: "Had + Subject + been + V-ing?",
    },
    examples: [
      { en: "I had been studying", uz: "Men o'qib kelayotgan edim" },
      { en: "He had been working", uz: "U ishlab kelayotgan edi" },
      { en: "They had been playing", uz: "Ular o'ynab kelayotgan edi" },
    ],
    rules: [
      "had been + V-ing",
      "Jarayon (davom) muhim",
    ],
    signalWords: ["for", "since", "before"],
    commonMistakes: [
      { wrong: "I had been study", correct: "I had been studying" },
      { wrong: "He had been work", correct: "He had been working" },
      { wrong: "I was been studying", correct: "I had been studying" },
    ],
    miniExercise: [
      { question: "Men 3 soat o'qib kelayotgan edim", answer: "I had been studying for 3 hours" },
      { question: "U ertalabdan beri ishlayotgan edi", answer: "He had been working since morning" },
      { question: "Sen qancha vaqtdan beri kutayotgan eding?", answer: "How long had you been waiting?" },
      { question: "Biz u kelishidan oldin o'ynab kelayotgan edik", answer: "We had been playing before he came" },
    ],
    practiceSentences: [
      "Men ikki soatdan beri kitob o'qib kelayotgan edim.",
      "U ertalabdan beri ishlab kelayotgan edi.",
      "Ular ancha vaqtdan beri futbol o'ynab kelishayotgan edi.",
      "Men charchagan edim, chunki yugurib kelgan edim.",
      "Siz qancha vaqtdan beri kutayotgan edingiz?",
      "Yomg'ir tun bo'yi yog'ib kelayotgan edi.",
      "Biz uzoq vaqtdan beri shu loyiha ustida ishlab kelayotgan edik.",
      "Ular uch kundan beri uxlamay kelishayotgan edi.",
      "Men bir yildan beri ingliz tilini o'rganib kelayotgan edim.",
      "U kelganida, men dars tayyorlayotgan edim."
    ],
    lifehack: "had been + V-ing | for/since = signal",
  },
  {
    id: "future-simple",
    title: "Future Simple",
    description: "Kelajakda bo'ladigan ishlar.",
    usage: ["Tez qaror", "Bashorat (prediction)", "Va'da / taklif"],
    formula: {
      positive: "Subject + will + V1",
      negative: "Subject + will not + V1",
      question: "Will + Subject + V1?",
    },
    examples: [
      { en: "I will study", uz: "Men o'qiyman" },
      { en: "He will work", uz: "U ishlaydi" },
      { en: "They will play", uz: "Ular o'ynaydi" },
    ],
    rules: [
      "Hamma subject bilan 'will' bir xil",
      "Har doim V1 ishlatiladi",
      "Tez qaror uchun 'will', reja uchun 'going to'",
    ],
    signalWords: ["tomorrow", "next week/year", "soon", "later"],
    commonMistakes: [
      { wrong: "I will goes", correct: "I will go" },
      { wrong: "He will going", correct: "He will go" },
      { wrong: "Will he goes?", correct: "Will he go?" },
    ],
    miniExercise: [
      { question: "Men ertaga o'qiyman", answer: "I will study tomorrow" },
      { question: "U kelmaydi", answer: "He won't come" },
      { question: "Sen yordam berasanmi?", answer: "Will you help?" },
      { question: "Biz keyin gaplashamiz", answer: "We will talk later" },
    ],
    practiceSentences: [
      "Men ertaga kitob o'qiyman.",
      "Ular keyingi hafta Toshkentga borishadi.",
      "Men sizga yordam beraman.",
      "Ertaga yomg'ir yog'adi.",
      "Siz menga qo'ng'iroq qilasizmi?",
      "U bugun kelmaydi.",
      "Biz tez orada uchrashamiz.",
      "Men sizni kutaman.",
      "Ular futbol o'ynashadi.",
      "Men buni qilmayman."
    ],
    lifehack: "will + V1 | hamma bilan bir xil",
  },
  {
    id: "future-continuous",
    title: "Future Continuous",
    description: "Kelajakda ma'lum bir vaqtda davom etayotgan ish.",
    usage: ["Aniq vaqt kelajakda", "Taxmin (guess)", "Rejalashtirilgan davomiy ish"],
    formula: {
      positive: "Subject + will be + V-ing",
      negative: "Subject + will not be + V-ing",
      question: "Will + Subject + be + V-ing?",
    },
    examples: [
      { en: "I will be studying", uz: "Men o'qiyotgan bo'laman" },
      { en: "He will be working", uz: "U ishlayotgan bo'ladi" },
      { en: "They will be playing", uz: "Ular o'ynayotgan bo'ladi" },
    ],
    rules: [
      "will be + V-ing",
      "Kelajak + davom = Future Continuous",
    ],
    signalWords: ["at this time tomorrow", "at 5 pm tomorrow", "next week", "soon"],
    commonMistakes: [
      { wrong: "I will be study", correct: "I will be studying" },
      { wrong: "He will be work", correct: "He will be working" },
      { wrong: "Will he be studies?", correct: "Will he be studying?" },
    ],
    miniExercise: [
      { question: "Men ertaga shu paytda o'qiyotgan bo'laman", answer: "I will be studying at this time tomorrow" },
      { question: "U ishlamayotgan bo'ladi", answer: "He will not be working" },
      { question: "Sen kutayotgan bo'lasanmi?", answer: "Will you be waiting?" },
      { question: "Biz safarda bo'layotgan bo'lamiz", answer: "We will be traveling" },
    ],
    practiceSentences: [
      "Men ertaga soat 8 da kitob o'qiyotgan bo'laman.",
      "Ular futbol o'ynayotgan bo'lishadi.",
      "Siz ertaga nima qilayotgan bo'lasiz?",
      "U uxlayotgan bo'ladi.",
      "Biz dars tayyorlayotgan bo'lamiz.",
      "Ular gaplashib o'tirishgan bo'lishadi.",
      "Men sizni kutayotgan bo'laman.",
      "U ertaga ishlayotgan bo'ladi.",
      "Siz darsda bo'lasizmi?",
      "Men u yerda bo'lmayman."
    ],
    lifehack: "will be + V-ing = kelajak + davom",
  },
  {
    id: "future-perfect",
    title: "Future Perfect",
    description: "Kelajakda ma'lum bir vaqtgacha ish tugagan bo'ladi.",
    usage: ["Kelajakda deadline", "Kelajakdagi natija"],
    formula: {
      positive: "Subject + will have + V3",
      negative: "Subject + will not have + V3",
      question: "Will + Subject + have + V3?",
    },
    examples: [
      { en: "I will have finished", uz: "Men tugatgan bo'laman" },
      { en: "He will have gone", uz: "U ketgan bo'ladi" },
      { en: "They will have done", uz: "Ular qilgan bo'ladi" },
    ],
    rules: [
      "will have + V3",
      "by (gacha) signali ko'p ishlatiladi",
    ],
    signalWords: ["by tomorrow", "by next week", "by 2026"],
    commonMistakes: [
      { wrong: "I will have went", correct: "I will have gone" },
      { wrong: "He will has finished", correct: "He will have finished" },
      { wrong: "I will have finish", correct: "I will have finished" },
    ],
    miniExercise: [
      { question: "Men ertagacha ishni tugatgan bo'laman", answer: "I will have finished by tomorrow" },
      { question: "U kelgan bo'ladi", answer: "He will have come" },
      { question: "Sen vazifani tugatgan bo'lasanmi?", answer: "Will you have finished?" },
      { question: "Biz keyingi haftagacha bitirgan bo'lamiz", answer: "We will have finished by next week" },
    ],
    practiceSentences: [
      "Men ertagacha uy vazifamni tugatgan bo'laman.",
      "Ular keyingi haftagacha Toshkentga borib bo'lishadi.",
      "Men soat 9 gacha ishni bitirgan bo'laman.",
      "Siz u kelguncha ovqat pishirib bo'lasizmi?",
      "U ertagacha kelgan bo'ladi.",
      "Biz darsni tugatgan bo'lamiz.",
      "Ular hamma narsani hal qilib bo'lishadi.",
      "Men kitobni o'qib bo'lgan bo'laman.",
      "Siz u yerda bo'lasizmi?",
      "U hali bitirmagan bo'ladi."
    ],
    lifehack: "will have + V3 | by = 90% shu zamon",
  },
  {
    id: "future-perfect-continuous",
    title: "Future Perfect Continuous",
    description: "Kelajakda ma'lum bir vaqtgacha ish qancha vaqt davom etgan bo'ladi.",
    usage: ["Davomiylik + kelajak", "since / for / by bilan"],
    formula: {
      positive: "Subject + will have been + V-ing",
      negative: "Subject + will not have been + V-ing",
      question: "Will + Subject + have been + V-ing?",
    },
    examples: [
      { en: "I will have been studying", uz: "Men o'qib kelayotgan bo'laman" },
      { en: "He will have been working", uz: "U ishlab kelayotgan bo'ladi" },
      { en: "They will have been playing", uz: "Ular o'ynab kelayotgan bo'ladi" },
    ],
    rules: [
      "will have been + V-ing",
      "Davomiylik (jarayon) muhim",
    ],
    signalWords: ["for", "since", "by"],
    commonMistakes: [
      { wrong: "I will have been study", correct: "I will have been studying" },
      { wrong: "He will has been working", correct: "He will have been working" },
      { wrong: "I will have been worked", correct: "I will have been working" },
    ],
    miniExercise: [
      { question: "Men 2 soat o'qib kelayotgan bo'laman", answer: "I will have been studying for 2 hours" },
      { question: "U ertalabdan beri ishlayotgan bo'ladi", answer: "He will have been working since morning" },
      { question: "Sen qancha vaqtdan beri kutayotgan bo'lasan?", answer: "How long will you have been waiting?" },
      { question: "Biz kechagacha ishlayotgan bo'lamiz", answer: "We will have been working by yesterday" },
    ],
    practiceSentences: [
      "Men ertaga soat 9 da ikki soatdan beri kitob o'qiyotgan bo'laman.",
      "U ertalabdan beri ishlab kelayotgan bo'ladi.",
      "Ular ancha vaqtdan beri futbol o'ynab kelishayotgan bo'ladi.",
      "Siz qancha vaqtdan beri kutayotgan bo'lasiz?",
      "Yomg'ir tun bo'yi yog'ib kelayotgan bo'ladi.",
      "Biz uzoq vaqtdan beri shu loyiha ustida ishlab kelayotgan bo'lamiz.",
      "Ular uch kundan beri uxlamay kelishayotgan bo'ladi.",
      "Men bir yildan beri ingliz tilini o'rganib kelayotgan bo'laman.",
      "U kelganida, men dars tayyorlayotgan bo'laman.",
      "Siz u yerda bo'lasizmi?"
    ],
    lifehack: "will have been + V-ing | for / since / by = signal",
  },
];
